name: Images Deploy

on:
  push:
    branches: 
      - master
    paths:
      - 'images/**'

jobs:
  deploy_images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync Images
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: vanilla-extract
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        with:
          args: -m rsync -d -r images gs://vanilla-extract.appspot.com/packfiles/
          cli: gsutil
